# Generated by Django 2.2.7 on 2019-11-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('text', models.CharField(max_length=1000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_image_url', models.CharField(max_length=100)),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
